### ISSUE TITLE
组装机配方冲突

### ISSUE THREAD

**Issue by whaterrow** [KeQingsocute520/GT-QuantumTransition#67]
电烙铁头与阀门共用组装机20号电路,且阀门含有电烙铁头所需材料
![屏幕截图 2024-12-05 092519](https://github.com/user-attachments/assets/83887170-ea7c-4773-aa0a-73cb8713e11f)
![屏幕截图 2024-12-05 092549](https://github.com/user-attachments/assets/ee2c5fcb-2994-4df5-8a80-c01bba377c90)

**Comment by MeowmelMuku** [comment]
了解

**Comment by whaterrow** [comment]
实际上不会冲突,是我铸币了:(
